

export const Products = [
  {
    name: "T-shirt",
    description: "A casual and comfortable garment that covers the upper body and has short sleeves and a round neck. It can be made from cotton, polyester, or other fabrics and have various colors, patterns, or logos.",
    image: "https://th.bing.com/th/id/OIP.omIRA7NIb8Gj-OTVvW6XggHaH8?pid=ImgDet&rs=1",
    price: 9.99,
    category: "clothes",
  },
  {
    name: "Jeans",
    description: "A durable and versatile garment that covers the lower body and has pockets and a zipper. It can be made from denim, corduroy, or other materials and have different styles, such as skinny, bootcut, or flare.",
    image: "https://th.bing.com/th/id/OIP.CpaqrbQao0WoeyDo9OiwNAHaMJ?pid=ImgDet&rs=1",
    price: 49.99,
    category: "clothes",
  },
  {
    name: "Dress",
    description: "A feminine and elegant garment that covers the whole body and has a skirt and a bodice. It can be made from silk, cotton, lace, or other fabrics and have different lengths, such as mini, midi, or maxi.",
    image: "https://th.bing.com/th/id/OIP.jHhyyBefVFJvxJ3e2_6b3AHaKg?pid=ImgDet&rs=1",
    price: 69.99,
    category: "clothes",
  },
  {
    name: "Sweater",
    description: "A warm and cozy garment that covers the upper body and has long sleeves and a collar. It can be made from wool, acrylic, or other fibers and have different textures, such as knit, crochet, or fleece.",
    image: "https://th.bing.com/th/id/OIP.46kCyD-UHd5jlvLbXW5a4QHaHa?pid=ImgDet&rs=1",
    price: 39.99,
    category: "clothes",
  },
  {
    name: "Jacket",
    description: "A protective and stylish garment that covers the upper body and has long sleeves and a zipper or buttons. It can be made from leather, denim, nylon, or other materials and have different features, such as a hood, pockets, or cuffs.",
    image: "https://i5.walmartimages.com/asr/b24fd818-827e-4ffb-8d5b-7106e61491d9_1.5c3d273a4800b6f3337e82da0861f2fa.jpeg",
    price: 79.99,
    category: "clothes",
  },
  {
    name: "Skirt",
    description: "A fashionable and flattering garment that covers the lower body and has a waistband and a hem. It can be made from cotton, linen, or other fabrics and have different shapes, such as pencil, A-line, or pleated.",
    image: "https://th.bing.com/th/id/OIP.gHYtXH0zyqzaUgQ2zPRJNgHaHa?pid=ImgDet&rs=1",
    price: 29.99,
    category: "clothes",
  },
  {
    name: "Shirt",
    description: "A formal and professional garment that covers the upper body and has long sleeves and a collar. It can be made from cotton, polyester, or other fabrics and have different colors, such as white, blue, or black.",
    image: "https://purepng.com/public/uploads/large/purepng.com-mens-stylish-shirt-bluebutton-front-shirtgarmentdressshirtfullmensstylishblue-1421526306983zzdmy.png",
    price: 19.99,
    category: "clothes",
  },
  {
    name: "jean Pants",
    description: "A practical and comfortable garment that covers the lower body and has pockets and a belt loop. It can be made from cotton, khaki, or other materials and have different cuts, such as straight, slim, or wide.",
    image: "https://purepng.com/public/uploads/large/jeans-pant-xom.png",
    price: 59.99,
    category: "clothes",
  },
  {
    name: "Dress Shirt",
    description: "A formal and professional garment that covers the upper body and has long sleeves and a collar. It can be made from cotton, polyester, or other fabrics and have different colors, such as white, blue, or black.",
    image: "https://th.bing.com/th/id/OIP.8w6LI2__NeTnHkQo2AgyTAHaJM?pid=ImgDet&rs=1",
    price: 19.99,
    category: "clothes",
  },
  {
    name: "Pants",
    description: "A practical and comfortable garment that covers the lower body and has pockets and a belt loop. It can be made from cotton, khaki, or other materials and have different cuts, such as straight, slim, or wide.",
    image: "[Image]",
    price: 59.99,
    category: "clothes",
  },
  {
    name: "Socks",
    description: "A soft and cozy garment that covers the feet and ankles and keeps them warm and dry. They can be made from wool, cotton, or other fibers and have different patterns, such as stripes, dots, or checks.",
    image: "[Image]",
    price: 4.99,
    category: "clothes",
  },
  {
    name: "Hat",
    description: "A stylish and functional garment that covers the head and protects it from the sun, rain, or cold. It can be made from straw, wool, leather, or other materials and have different shapes, such as a fedora, baseball cap, or beanie.",
    image: "[Image]",
    price: 14.99,
    category: "clothes",
  },
  {
    name: "Shoes",
    description: "A durable and comfortable garment that covers the feet and provides support and traction. They can be made from leather, rubber, canvas, or other materials and have different types, such as sneakers, boots, or sandals.",
    image: "[Image]",
    price: 69.99,
    category: "clothes",
  },
  {
    name: "Laptop",
    description: "A portable computer that can be used for various tasks such as browsing the web, writing documents, playing games, or watching videos. It has a keyboard, a touchpad, a screen, and a battery. It can run different operating systems such as Windows, Mac OS, or Linux.",
    image: "[Image]",
    price: 999.99,
    category: "electronics",
  },
  {
    name: "Smartphone",
    description: "A handheld device that can make phone calls, send messages, access the internet, take photos, play music, and use various apps. It has a touchscreen, a camera, a speaker, a microphone, and a battery. It can run different operating systems such as Android, iOS, or Windows Phone.",
    image: "[Image]",
    price: 699.99,
    category: "electronics",
  },
  {
    name: "Tablet",
    description: "A larger version of a smartphone that can be used for similar purposes but with a bigger screen and more features. It has a touchscreen, a camera, a speaker, a microphone, and a battery. It can run different operating systems such as Android, iOS, or Windows.",
    image: "[Image]",
    price: 499.99,
    category: "electronics",
  },
  {
    name: "Smartwatch",
    description: "A wearable device that can be paired with a smartphone to display notifications, track fitness, monitor health, control music, and use various apps. It has a touchscreen, a sensor, a speaker, a microphone, and a battery. It can run different operating systems such as Android Wear, Apple Watch OS, or Tizen.",
    image: "[Image]",
    price: 299.99,
    category: "electronics",
  },
  {
    name: "Headphones",
    description: "A pair of devices that can be worn over the ears to listen to audio from various sources such as a smartphone, a laptop, or an MP3 player. They can be wired or wireless and have different features such as noise cancellation, bass boost, or surround sound.",
    image: "[Image]",
    price: 199.99,
    category: "electronics",
  },
  {
    name: "Bluetooth Speaker",
    description: "A wireless device that can be connected to a smartphone, a tablet, or a laptop to play audio from various sources such as music streaming services, podcasts, or radio stations. It has a speaker, a battery, and an LED light. It can be waterproof, portable, or smart.",
    image: "[Image]",
    price: 149.99,
    category: "electronics",
  },
  {
    name: "Digital Camera",
    description: "A device that can capture images and videos of high quality and store them on a memory card or upload them to the cloud. It has a lens, a sensor, a flash, a screen, and a battery. It can have different modes such as auto, manual, portrait, or landscape.",
    image: "[Image]",
    price: 399.99,
    category: "electronics",
  },
  {
    name: "Drone",
    description: "A flying device that can be controlled remotely or autonomously to perform various tasks such as aerial photography, delivery, surveillance, or entertainment. It has a camera, a propeller, a battery, and a GPS. It can have different sizes, shapes, and features.",
    image: "[Image]",
    price: 199.99,
    category: "electronics",
  },
  {
    name: "Electric Toothbrush",
    description: "A device that can clean the teeth and gums more effectively and gently than a manual toothbrush. It has a brush head, a motor, a battery, and a charger. It can have different modes, such as whitening, sensitive, or massage.",
    image: "[Image]",
    price: 49.99,
    category: "electronics",
  },
  {
    name: "Gaming Console",
    description: "A device that can play video games on a TV or monitor. It has a controller, a processor, a memory, and a disk drive. It can run different platforms, such as PlayStation, Xbox, or Nintendo.",
    image: "[Image]",
    price: 399.99,
    category: "electronics",
  },
  {
    name: "Apple Pie",
    description: "A sweet dessert made from apples, sugar, cinnamon, and pastry. It is usually served with whipped cream or ice cream. It is a popular dish in many countries, especially in the United States and the United Kingdom.",
    image: "[Image]",
    price: 4.99,
    category: "foodItems",
  },
  {
    name: "Biryani",
    description: "A spicy rice dish with meat, vegetables, and various spices. It is a staple food in many parts of South Asia and the Middle East. It can be made with chicken, lamb, beef, or seafood.",
    image: "[Image]",
    price: 8.99,
    category: "foodItems",
  },
  {
    name: "Cheeseburger",
    description: "A sandwich consisting of a cooked beef patty, cheese, lettuce, tomato, onion, and other toppings, served on a bun. It is one of the most common fast food items in the world. It can be paired with fries, salad, or coleslaw.",
    image: "[Image]",
    price: 5.99,
    category: "foodItems",
  },
  {
    name: "Dim Sum",
    description: "A variety of small dishes that are steamed, fried, or baked. They are usually served in bamboo baskets or on small plates. They are a part of Chinese cuisine and are often eaten for breakfast or brunch. Some common dim sum dishes are dumplings, buns, spring rolls, and spare ribs.",
    image: "[Image]",
    price: 9.99,
    category: "foodItems",
  },
  {
    name: "Eggplant Parmesan",
    description: "A baked dish made from sliced eggplant, tomato sauce, cheese, and herbs. It is a vegetarian dish that originated in Italy. It can be served as a main course or a side dish.",
    image: "[Image]",
    price: 7.99,
    category: "foodItems",
  },
  {
    name: "French Fries",
    description: "Thinly sliced potatoes that are deep-fried and seasoned with salt. They are a popular snack or side dish that originated in Belgium. They can be dipped in ketchup, mayonnaise, or other sauces.",
    image: "[Image]",
    price: 2.99,
    category: "foodItems",
  },
  {
    name: "Green Salad",
    description: "A fresh and healthy dish made from various types of lettuce, spinach, kale, and other greens. It can be topped with dressing, cheese, nuts, fruits, or vegetables. It is a good source of vitamins and minerals.",
    image: "[Image]",
    price: 4.99,
    category: "foodItems",
  },
  {
    name: "Hot Dog",
    description: "A cooked sausage that is usually served on a long bun with mustard, ketchup, relish, or other condiments. It is a common street food in many countries, especially in the United States and Germany. It can be made from beef, pork, chicken, or turkey.",
    image: "[Image]",
    price: 3.99,
    category: "foodItems",
  },
  {
    name: "Ice Cream",
    description: "A frozen dessert made from milk, cream, sugar, and various flavors. It can be scooped into cones, cups, or bowls. It can also be mixed with fruits, nuts, chocolate, or candy. It is a popular treat for hot days.",
    image: "[Image]",
    price: 3.99,
    category: "foodItems",
  },
  {
    name: "Jambalaya",
    description: "A spicy rice dish with chicken, sausage, shrimp, and vegetables. It is a traditional dish of Louisiana in the United States. It is influenced by French, Spanish, African, and Native American cuisines.",
    image: "[Image]",
    price: 9.99,
    category: "foodItems",
  },
  {
    name: "Soccer Ball",
    description: "A round and inflated ball that is used to play soccer, the most popular sport in the world. It is made from synthetic leather and has a black and white pattern. It has a diameter of about 22 cm and a weight of about 450 g.",
    image: "[Image]",
    price: 19.99,
    category: "sportsItems",
  },
  {
    name: "Tennis Racket",
    description: "A device that is used to hit a tennis ball in the sport of tennis. It has a handle, a frame, and a stringed net. It is made from wood, metal, or composite materials. It has a length of about 70 cm and a weight of about 300 g.",
    image: "[Image]",
    price: 49.99,
    category: "sportsItems",
  },
  {
    name: "Skateboard",
    description: "A board that is used to perform tricks and ride on various surfaces in the sport of skateboarding. It has a deck, four wheels, and two trucks. It is made from wood, plastic, or carbon fiber. It has a length of about 80 cm and a width of about 20 cm.",
    image: "[Image]",
    price: 99.99,
    category: "sportsItems",
  },
  {
    name: "Golf Club",
    description: "A tool that is used to hit a golf ball in the sport of golf. It has a shaft, a grip, and a head. It is made from steel, titanium, or graphite. It has a length of about 100 cm and a weight of about 400 g.",
    image: "[Image]",
    price: 149.99,
    category: "sportsItems",
  },
  {
    name: "Basketball Hoop",
    description: "A target that is used to score points in the sport of basketball. It has a rim, a net, and a backboard. It is made from metal, nylon, or acrylic. It has a diameter of about 45 cm and a height of about 3 m.",
    image: "[Image]",
    price: 199.99,
    category: "sportsItems",
  },
  {
    name: "Swimming Goggles",
    description: "A pair of eyewear that is used to protect the eyes and enhance the vision in the water in the sport of swimming. They have a frame, a lens, a strap, and a seal. They are made from plastic, rubber, or silicone. They have different colors, shapes, and sizes.",
    image: "[Image]",
    price: 19.99,
    category: "sportsItems",
  },
  {
    name: "Boxing Gloves",
    description: "A pair of padded gloves that is used to protect the hands and reduce the impact of punches in the sport of boxing. They have a thumb, a knuckle, a wrist, and a lace or velcro. They are made from leather, vinyl, or synthetic materials. They have different weights, such as 8 oz, 10 oz, or 12 oz.",
    image: "[Image]",
    price: 49.99,
    category: "sportsItems",
  },
  {
    name: "Ski",
    description: "A long and narrow board that is used to glide on snow in the sport of skiing. It has a tip, a tail, an edge, and a binding. It is made from wood, metal, or composite materials. It has different lengths, widths, and shapes, depending on the type of skiing.",
    image: "[Image]",
    price: 99.99,
    category: "sportsItems",
  },
  {
    name: "Hockey Stick",
    description: "A long and curved tool that is used to hit a hockey puck in the sport of hockey. It has a shaft, a blade, and a grip. It is made from wood, fiberglass, or carbon fiber. It has different lengths, angles, and flexes, depending on the position and preference of the player.",
    image: "[Image]",
    price: 149.99,
    category: "sportsItems",
  },
  {
    name: "Bicycle",
    description: "A two-wheeled vehicle that is used to ride on various terrains in the sport of cycling. It has a frame, a handlebar, a seat, pedals, brakes, gears, and tires. It is made from steel, aluminum, or carbon fiber. It has different types, such as road bike, mountain bike, or BMX bike.",
    image: "[Image]",
    price: 199.99,
    category: "sportsItems",
  },
]